# Generated by Django 6.1 on 2026-08-16 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Clear headline for the item (e.g., 'Blue Dell Laptop Bag', 'Student ID Card')", max_length=200)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics & Gadgets (Phones, Laptops, Earbuds, Chargers)'), ('CARDS_ID', 'Student IDs, Bank Cards & Badges'), ('KEYS', 'Keys & Keychains'), ('BAGS_WALLETS', 'Bags, Backpacks & Wallets'), ('BOOKS_DOCS', 'Books, Notebooks & Documents'), ('CLOTHING', 'Clothing, Jackets & Hats'), ('ACCESSORIES', 'Watches, Glasses & Jewelry'), ('SPORTS_BOTTLES', 'Water Bottles & Sports Equipment'), ('OTHER', 'Other Miscellaneous Items')], default='OTHER', max_length=50)),
                ('status', models.CharField(choices=[('LOST', 'Lost Item'), ('FOUND', 'Found Item'), ('CLAIMED', 'Claimed / Reunited')], db_index=True, default='LOST', max_length=20)),
                ('location', models.CharField(help_text='Campus area, building, room number, or landmark where it was lost or found', max_length=200)),
                ('date_event', models.DateField(default=django.utils.timezone.now, help_text='Approximate date when the item was lost or found', verbose_name='Date Lost/Found')),
                ('description', models.TextField(help_text='Detailed description including brand, color, distinguishing marks, stickers, or contents')),
                ('contact', models.CharField(help_text='Contact email, phone number, WhatsApp, or designated campus drop-off office', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Photo of the item (stored securely on Amazon S3 in cloud deployment)', null=True, upload_to='item_images/%Y/%m/')),
                ('is_verified_returned', models.BooleanField(default=False, help_text='Designates whether the item has been successfully returned to its rightful owner')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the item was marked as claimed/reunited', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The campus user who reported this item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campus Item',
                'verbose_name_plural': 'Campus Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
