# Generated by Django 6.1 on 2026-08-16 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the item was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='The user or administrator who deleted this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Audited justification provided when item was deleted', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag allowing recovery by administrators'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_ACTIVATED', 'User Account Activated'), ('USER_DEACTIVATED', 'User Account Deactivated'), ('ROLE_PROMOTED', 'Role / Permission Promoted'), ('ROLE_DEMOTED', 'Role / Permission Demoted'), ('PASSWORD_RESET', 'Password Reset Triggered'), ('ITEM_SOFT_DELETED', 'Item Soft Deleted'), ('ITEM_HARD_DELETED', 'Item Permanently Deleted'), ('ITEM_RESTORED', 'Item Restored'), ('SETTING_CHANGED', 'System Setting Modified'), ('ALERT_RESOLVED', 'Security Alert Resolved'), ('BULK_OPERATION', 'Bulk Data Operation'), ('ADMIN_LOGIN', 'Admin Portal Sign In')], db_index=True, max_length=60)),
                ('target_model', models.CharField(blank=True, help_text='Model affected (e.g., User, Item, SystemSetting)', max_length=60)),
                ('target_id', models.CharField(blank=True, help_text='ID of target object', max_length=60)),
                ('target_repr', models.CharField(blank=True, help_text='Human-readable title/name of the target object', max_length=255)),
                ('reason', models.TextField(blank=True, help_text='Mandatory justification captured for high-risk operations')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Contextual metadata, old vs new values diff')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The administrator or system user who triggered this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical Alert')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Alert',
                'verbose_name_plural': 'Security Alerts',
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=60, unique=True)),
                ('value', models.TextField(help_text='Current configuration value')),
                ('description', models.CharField(help_text='Operational purpose of this setting', max_length=255)),
                ('data_type', models.CharField(choices=[('bool', 'Boolean (True/False)'), ('int', 'Integer Number'), ('str', 'Short Text'), ('text', 'Long Text / Notice')], default='str', max_length=20)),
                ('category', models.CharField(default='General', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
